<div align="center">
<noindex>
<!-- begin of Top100 logo -->
<a rel="nofollow" href="http://top100.rambler.ru/top100/"><img src="http://top100-images.rambler.ru/top100/banner-88x31-rambler-blue3.gif" alt="Rambler's Top100" width="88" height="31" border="0" /></a>
<!-- end of Top100 logo -->
&nbsp;&nbsp;&nbsp;

<a rel="nofollow" href="http://www.tatar.ru"><img src="http://almetguide.ru/images/tatar.gif" alt="Сервер Республики Татарстан" width="88" height="31" border="0"> </a>	
	  &nbsp;&nbsp;&nbsp;

<a rel="nofollow" href='http://www.gismeteo.ru/city/daily/11940'><img src='http://informer.gismeteo.Ru/99954-30.GIF' alt="GISMETEO: Погода по г. Альметьевск" border="0"></a>
&nbsp;&nbsp;&nbsp;
<object type="application/x-shockwave-flash" data="http://medvedev-da.ru/bn/swf/mda.swf" width="120"   height="60">
		      <param name="movie" value="http://medvedev-da.ru/bn/swf/mda.swf">
              <param name="quality" value="best">
</object>
	&nbsp;&nbsp;&nbsp;
      
	  <a rel="nofollow" href="http://www.almat-info.ru"><img src="http://almetguide.ru/images/almat.jpg" alt="Сайт г. Альметьевск" width="88" height="32" border="0"></a>
&nbsp;&nbsp;&nbsp;
	  

<!--LiveInternet counter--><script type="text/javascript"><!--
document.write("<a href='http://www.liveinternet.ru/click' "+
"target=_blank><img src='http://counter.yadro.ru/hit?t22.10;r"+
escape(document.referrer)+((typeof(screen)=="undefined")?"":
";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?
screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+
";"+Math.random()+
"' alt='' title='LiveInternet: показано число просмотров за 24"+
" часа, посетителей за 24 часа и за сегодня' "+
"border='0' width='88' height='31'><\/a>")
//--></script><!--/LiveInternet-->



</noindex>   

</div>