&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<marquee height=50 width=75%
	hspace=5
	vspace=5
	align=top
	direction=left
	loop=infinity
	behavior=scroll
	scrollamount=5
	scrolldelay=100 >

<strong>Сервисный центр расположен по адресу: Альметьевск, Ул. Клары Цеткин 18а   Тел. 322211, 371789 </strong>
</marquee>
